/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnTlbRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 640));
        setPreferredSize(new java.awt.Dimension(890, 640));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setRollover(true);

        btnTlbRegistro.setBackground(new java.awt.Color(102, 102, 102));
        btnTlbRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnTlbRegistro.setText("Registro");
        btnTlbRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTlbRegistro.setFocusable(false);
        btnTlbRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTlbRegistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnTlbRegistro);

        jLabel1.setText(" ");
        jToolBar1.add(jLabel1);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 35));

        pnlFondo.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("Farmacias");
        pnlFondo.add(jLabel2);
        jLabel2.setBounds(360, 40, 280, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alpjha.png"))); // NOI18N
        pnlFondo.add(jLabel3);
        jLabel3.setBounds(310, 220, 370, 190);

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 890, 610));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(54, 35));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPnlFondo() {
        return pnlFondo;
    }

    public void setPnlFondo(JPanel pnlFondo) {
        this.pnlFondo = pnlFondo;
    }



    public JButton getBtnTlbRegistro() {
        return btnTlbRegistro;
    }

    public void setBtnTlbRegistro(JButton btnTlbRegistro) {
        this.btnTlbRegistro = btnTlbRegistro;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTlbRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
