/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class VistaRegistro extends javax.swing.JPanel {

    /**
     * Creates new form VistaRegistro
     */
    public VistaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDistri = new javax.swing.ButtonGroup();
        pnlPedido = new javax.swing.JPanel();
        lblPnlPedidoTitle = new javax.swing.JLabel();
        lblPnlPedidoCuerpo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblPnlPedidoPie = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnPnlPedCan = new javax.swing.JButton();
        btnPnlPedEnv = new javax.swing.JButton();
        lblPedido = new javax.swing.JLabel();
        pnlRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidadMedi = new javax.swing.JTextField();
        cmbTipoMed = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombreMedi = new javax.swing.JTextField();
        rdbCofar = new javax.swing.JRadioButton();
        rdbEmp = new javax.swing.JRadioButton();
        rdbCem = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chcPrincipal = new javax.swing.JCheckBox();
        chcSecundario = new javax.swing.JCheckBox();
        btnPnlRegOk = new javax.swing.JButton();
        lblAlertNomMedVac = new javax.swing.JLabel();
        lblAlertCantProdVac = new javax.swing.JLabel();
        lblAlertCantProdLet = new javax.swing.JLabel();
        lblAlertCantProdNeg = new javax.swing.JLabel();
        lblAlertNomMedNum = new javax.swing.JLabel();
        lblAlertSucurVac = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPnlPedidoTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlPedido.add(lblPnlPedidoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 440, 30));

        lblPnlPedidoCuerpo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pnlPedido.add(lblPnlPedidoCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 430, 30));
        pnlPedido.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 450, 10));
        pnlPedido.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 440, 40));
        pnlPedido.add(lblPnlPedidoPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 440, 80));
        pnlPedido.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 430, 40));

        btnPnlPedCan.setText("Cancelar");
        pnlPedido.add(btnPnlPedCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        btnPnlPedEnv.setText("Enviar");
        pnlPedido.add(btnPnlPedEnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));
        pnlPedido.add(lblPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 290, 30));

        add(pnlPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 570));

        pnlRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nombre Medicamento");
        pnlRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 30));
        pnlRegistro.add(txtCantidadMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 180, 40));

        cmbTipoMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibiótico" }));
        pnlRegistro.add(cmbTipoMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 170, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tipo Medicamento");
        pnlRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Cantidad del producto");
        pnlRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 30));
        pnlRegistro.add(txtnombreMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 40));

        btnGroupDistri.add(rdbCofar);
        rdbCofar.setText("Cofarma");
        rdbCofar.setName("a"); // NOI18N
        pnlRegistro.add(rdbCofar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        btnGroupDistri.add(rdbEmp);
        rdbEmp.setText("Empsephar");
        rdbEmp.setName("b"); // NOI18N
        pnlRegistro.add(rdbEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        btnGroupDistri.add(rdbCem);
        rdbCem.setText("Cemefar");
        rdbCem.setName("c"); // NOI18N
        pnlRegistro.add(rdbCem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Distribuidor");
        pnlRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Sucursal");
        pnlRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setText("Registro Pedidos");
        pnlRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        chcPrincipal.setText("Principal");
        pnlRegistro.add(chcPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        chcSecundario.setText("Secundaria");
        pnlRegistro.add(chcSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        btnPnlRegOk.setText("Ok");
        pnlRegistro.add(btnPnlRegOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));

        lblAlertNomMedVac.setForeground(new java.awt.Color(204, 0, 255));
        lblAlertNomMedVac.setText("Campo Vacío");
        pnlRegistro.add(lblAlertNomMedVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        lblAlertCantProdVac.setForeground(new java.awt.Color(204, 0, 204));
        lblAlertCantProdVac.setText("Campo Vacío");
        pnlRegistro.add(lblAlertCantProdVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        lblAlertCantProdLet.setForeground(new java.awt.Color(255, 102, 0));
        lblAlertCantProdLet.setText("Contiene letras");
        pnlRegistro.add(lblAlertCantProdLet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        lblAlertCantProdNeg.setForeground(new java.awt.Color(204, 0, 0));
        lblAlertCantProdNeg.setText("Número negativo o 0");
        pnlRegistro.add(lblAlertCantProdNeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        lblAlertNomMedNum.setForeground(new java.awt.Color(255, 102, 0));
        lblAlertNomMedNum.setText("Contiene números o espacios");
        pnlRegistro.add(lblAlertNomMedNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 250, -1));

        lblAlertSucurVac.setForeground(new java.awt.Color(153, 0, 204));
        lblAlertSucurVac.setText("Seleccione una sucursal");
        pnlRegistro.add(lblAlertSucurVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        add(pnlRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 570));
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnPnlRegOk() {
        return btnPnlRegOk;
    }

    public void setBtnPnlRegOk(JButton btnPnlRegOk) {
        this.btnPnlRegOk = btnPnlRegOk;
    }

    public JTextField getTxtCantidadMedi() {
        return txtCantidadMedi;
    }

    public void setTxtCantidadMedi(JTextField txtCantidadMedi) {
        this.txtCantidadMedi = txtCantidadMedi;
    }

    public JLabel getLblAlertCantProdLet() {
        return lblAlertCantProdLet;
    }

    public void setLblAlertCantProdLet(JLabel lblAlertCantProdLet) {
        this.lblAlertCantProdLet = lblAlertCantProdLet;
    }

    public JLabel getLblAlertCantProdNeg() {
        return lblAlertCantProdNeg;
    }

    public void setLblAlertCantProdNeg(JLabel lblAlertCantProdNeg) {
        this.lblAlertCantProdNeg = lblAlertCantProdNeg;
    }

    public JLabel getLblAlertCantProdVac() {
        return lblAlertCantProdVac;
    }

    public void setLblAlertCantProdVac(JLabel lblAlertCantProdVac) {
        this.lblAlertCantProdVac = lblAlertCantProdVac;
    }


    public JLabel getLblAlertNomMedNum() {
        return lblAlertNomMedNum;
    }

    public void setLblAlertNomMedNum(JLabel lblAlertNomMedNum) {
        this.lblAlertNomMedNum = lblAlertNomMedNum;
    }

    public JLabel getLblAlertNomMedVac() {
        return lblAlertNomMedVac;
    }

    public void setLblAlertNomMedVac(JLabel lblAlertNomMedVac) {
        this.lblAlertNomMedVac = lblAlertNomMedVac;
    }

    public JLabel getLblAlertSucurVac() {
        return lblAlertSucurVac;
    }

    public void setLblAlertSucurVac(JLabel lblAlertSucurVac) {
        this.lblAlertSucurVac = lblAlertSucurVac;
    }

    public JTextField getTxtnombreMedi() {
        return txtnombreMedi;
    }

    public void setTxtnombreMedi(JTextField txtnombreMedi) {
        this.txtnombreMedi = txtnombreMedi;
    }

    public JRadioButton getRdbCem() {
        return rdbCem;
    }

    public void setRdbCem(JRadioButton rdbCem) {
        this.rdbCem = rdbCem;
    }

    public JRadioButton getRdbCofar() {
        return rdbCofar;
    }

    public void setRdbCofar(JRadioButton rdbCofar) {
        this.rdbCofar = rdbCofar;
    }

    public JRadioButton getRdbEmp() {
        return rdbEmp;
    }

    public void setRdbEmp(JRadioButton rdbEmp) {
        this.rdbEmp = rdbEmp;
    }

    public JCheckBox getChcPrincipal() {
        return chcPrincipal;
    }

    public void setChcPrincipal(JCheckBox chcPrincipal) {
        this.chcPrincipal = chcPrincipal;
    }

    public JCheckBox getChcSecundario() {
        return chcSecundario;
    }

    public void setChcSecundario(JCheckBox chcSecundario) {
        this.chcSecundario = chcSecundario;
    }

    public JComboBox<String> getCmbTipoMed() {
        return cmbTipoMed;
    }

    public void setCmbTipoMed(JComboBox<String> cmbTipoMed) {
        this.cmbTipoMed = cmbTipoMed;
    }

    public ButtonGroup getBtnGroupDistri() {
        return btnGroupDistri;
    }

    public void setBtnGroupDistri(ButtonGroup btnGroupDistri) {
        this.btnGroupDistri = btnGroupDistri;
    }

    public JLabel getLblPnlPedidoCuerpo() {
        return lblPnlPedidoCuerpo;
    }

    public void setLblPnlPedidoCuerpo(JLabel lblPnlPedidoCuerpo) {
        this.lblPnlPedidoCuerpo = lblPnlPedidoCuerpo;
    }

    public JLabel getLblPnlPedidoPie() {
        return lblPnlPedidoPie;
    }

    public void setLblPnlPedidoPie(JLabel lblPnlPedidoPie) {
        this.lblPnlPedidoPie = lblPnlPedidoPie;
    }

    public JLabel getLblPnlPedidoTitle() {
        return lblPnlPedidoTitle;
    }

    public void setLblPnlPedidoTitle(JLabel lblPnlPedidoTitle) {
        this.lblPnlPedidoTitle = lblPnlPedidoTitle;
    }

    public JPanel getPnlPedido() {
        return pnlPedido;
    }

    public void setPnlPedido(JPanel pnlPedido) {
        this.pnlPedido = pnlPedido;
    }

    public JPanel getPnlRegistro() {
        return pnlRegistro;
    }

    public void setPnlRegistro(JPanel pnlRegistro) {
        this.pnlRegistro = pnlRegistro;
    }

    public JButton getBtnPnlPedCan() {
        return btnPnlPedCan;
    }

    public void setBtnPnlPedCan(JButton btnPnlPedCan) {
        this.btnPnlPedCan = btnPnlPedCan;
    }

    public JButton getBtnPnlPedEnv() {
        return btnPnlPedEnv;
    }

    public void setBtnPnlPedEnv(JButton btnPnlPedEnv) {
        this.btnPnlPedEnv = btnPnlPedEnv;
    }

    public JLabel getLblPedido() {
        return lblPedido;
    }

    public void setLblPedido(JLabel lblPedido) {
        this.lblPedido = lblPedido;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupDistri;
    private javax.swing.JButton btnPnlPedCan;
    private javax.swing.JButton btnPnlPedEnv;
    private javax.swing.JButton btnPnlRegOk;
    private javax.swing.JCheckBox chcPrincipal;
    private javax.swing.JCheckBox chcSecundario;
    private javax.swing.JComboBox<String> cmbTipoMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAlertCantProdLet;
    private javax.swing.JLabel lblAlertCantProdNeg;
    private javax.swing.JLabel lblAlertCantProdVac;
    private javax.swing.JLabel lblAlertNomMedNum;
    private javax.swing.JLabel lblAlertNomMedVac;
    private javax.swing.JLabel lblAlertSucurVac;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblPnlPedidoCuerpo;
    private javax.swing.JLabel lblPnlPedidoPie;
    private javax.swing.JLabel lblPnlPedidoTitle;
    private javax.swing.JPanel pnlPedido;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JRadioButton rdbCem;
    private javax.swing.JRadioButton rdbCofar;
    private javax.swing.JRadioButton rdbEmp;
    private javax.swing.JTextField txtCantidadMedi;
    private javax.swing.JTextField txtnombreMedi;
    // End of variables declaration//GEN-END:variables
}
